# servo_bridge:
#   ros__parameters:
#     topic: "/model/adeept_awr/joint/camera_servo_joint/cmd_vel"
#     ros_message_type: "std_msgs/msg/Float64"
#     gazebo_message_type: "gz.msgs.Double"

imu_bridge:
  ros__parameters:
    topic: "/gazebo/imu"
    ros_message_type: "sensor_msgs/msg/Imu"
    gazebo_message_type: "gz.msgs.IMU"

lidar_bridge:
  ros__parameters:
    topic: "/gazebo/scan"
    ros_message_type: "sensor_msgs/msg/LaserScan"
    gazebo_message_type: "gz.msgs.LaserScan"

ultrasonic_bridge:
  ros__parameters:
    topic: "/gazebo/raw/range"
    ros_message_type: "sensor_msgs/msg/LaserScan"
    gazebo_message_type: "gz.msgs.LaserScan"

camera_bridge:
  ros__parameters:
    topic: "/gazebo/camera"
    ros_message_type: "sensor_msgs/msg/Image"
    gazebo_message_type: "gz.msgs.Image"