/**/diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    
    left_wheel_names: ["left_motor_bracket_to_left_wheel"]
    right_wheel_names: ["right_motor_bracket_to_right_wheel"]
    wheel_separation: 0.213
    wheel_radius: 0.0345

    odom_frame_id: odom
    base_frame_id: base_link
    enable_odom_tf: false
