/**/ultrasonic_interpreter:
  ros__parameters:
    gazebo_topic: "raw/range"
    ros_topic: "range"

/**/image_compressor:
  ros__parameters:
    gazebo_topic: "camera/image"
    ros_topic: "camera/image_compressed"
