ultrasonic_interpreter:
  ros__parameters:
    gazebo_topic: "/gazebo/raw/range"
    ros_topic: "/gazebo/range"

image_compressor:
  ros__parameters:
    gazebo_topic: "/gazebo/camera"
    ros_topic: "/gazebo/camera_compressed"

# simulator_servo:
#   ros__parameters:
#     ros_action: "/put_servo_to_pos"
#     gazebo_topic: "/model/adeept_awr/joint/camera_servo_joint/cmd_vel"

